import React from 'react';
import { client } from '../../library/client';
import { useRouter } from 'next/router';
import Head from 'next/head';

const Topic = ({ result }) => {
  console.log(result);
  const router = useRouter();

  if (router.isFallback) {
    return <div>Loading</div>;
  } else {
    return (
      <div>
        <Head>
          <title>{result[0].name} | Topics Posts</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
      </div>
    );
  }
};

export default Topic;

export const getStaticPaths = async () => {
  const query = `*[_type == "topic"]{
  slug{
 current, 
}
}`;

  const query_paths = await client.fetch(query);

  const paths = query_paths.map((path) => ({
    params: {
      topic: path.slug.current,
    },
  }));

  return {
    paths,
    fallback: true,
  };
};

export const getStaticProps = async ({ params: { topic } }) => {
  const query = `*[_type == "topic" && slug.current == "${topic}"]{
  name,
  slug,
  "image": image.asset->url,
  body,
  _id,
  "post": *[_type == "post" && topic[0]->._id == ^._id][]{
  _id,
  author->,
  slug,
  topic[0]->,
  "image": mainImage.asset->url,
  category->,
  body,
  title,
  recommended_post,
  featured_post,
  publishedAt,
}
}`;

  const result = await client.fetch(query);

  if (!result) {
    return {
      error: true,
      data: [],
    };
  } else {
    return {
      props: {
        result,
      },
      revalidate: 10,
    };
  }
};
