import { NextAuthProvider } from '@/providers/next-auth';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ApolloProviderWrapper } from '@/components/apollo-provider-wrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <NextAuthProvider>
          <ApolloProviderWrapper>{children}</ApolloProviderWrapper>
        </NextAuthProvider>
      </body>
    </html>
  );
}
