import React from 'react';
import { useRouter } from 'next/router';
import { client } from '../../library/client';
import Head from 'next/head';

const Post = ({ result }) => {
  console.log(result);
  const router = useRouter();

  if (router.isFallback) {
    return <div>Loading</div>;
  } else {
    return (
      <h1>
        <Head>
          <title>{result.title} | Posts</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
      </h1>
    );
  }
};

export default Post;

export const getStaticPaths = async () => {
  const query = `*[_type == "post"]{
  slug{
  current
}
}`;

  const post_paths = await client.fetch(query);

  const paths = post_paths.map((path) => ({
    params: {
      post: path.slug.current,
    },
  }));

  return {
    paths,
    fallback: true,
  };
};

export const getStaticProps = async ({ params: { post } }) => {
  const postDetails = `*[_type == "post" && slug.current == "${post}"][0]{
  _id,
  publishedAt,
  title,
  slug,
  "image": mainImage.asset->url,
  featured_post,
  recommended_post,
  body,
  category->{
    name,
    slug,
    "image": image.asset->url,
  },
"topics": topic[]->{
  name,
  image,
  slug,
},
author->{
  name,
  slug,
  "image": image.asset->url,
}
}
`;

  const result = await client.fetch(postDetails);

  if (!result) {
    return {
      error: true,
      data: [],
    };
  } else {
    return {
      props: {
        result,
      },
      revalidate: 10,
    };
  }
};
