import React from 'react';
import Head from 'next/head';

const Category = () => {
  return (
    <div>
      <Head>
        <title>EoinDev Blog | Category</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  );
};

export default Category;
